on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Specifies that the job runs on a self-hosted runner
    runs-on: self-hosted

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v4

      # Logs into Docker Hub to allow pulling from/pushing to your Docker Hub repository
      # Docker Hub credentials are stored as GitHub secrets for security
      # - name: Log in to Docker Hub (if needed)
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Run Projects with Docker Compose
        working-directory: ./infrastructure/production
        run: |
          sudo docker-compose build
          sudo docker-compose up -d
